#!/bin/sh

PROJECT=`git rev-parse --show-toplevel`
echo "Running php-pre-commit hook in $PROJECT"

STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $STAGED_FILES_CMD
do
	php -l -d display_errors=0 $PROJECT/$FILE
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		exit 1
	fi
	FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
	echo "Running Code Sniffer..."
	./vendor/bin/phpcs --standard=ruleset.xml --encoding=utf-8 --colors -n -s -p $FILES
	if [ $? != 0 ]
	then
		echo "Coding standards errors have been detected. Running phpcbf..."
		./vendor/bin/phpcbf --standard=ruleset.xml --encoding=utf-8 -p $FILES
		git add $FILES
		echo "Running Code Sniffer again..."
		./vendor/bin/phpcs --standard=ruleset.xml --encoding=utf-8 --colors -s -n -p $FILES
		if [ $? != 0 ]
		then
			echo "Errors found not fixable automatically"
			exit 1
		fi
	fi

    echo "Running PHP Stan..."
    ./vendor/bin/phpstan --level=max --memory-limit=-1 analyse $FILES
fi


exit $?